### ISSUE TITLE
geometry column cannot be null

### ISSUE THREAD

**Issue by bjornreppen** [Stezii/tilestrata-postgismvt#1]
tilestrata-postgismvt fails for me and I don't know whether it's my data, my postgis install or a bug in tilestrata-postgismvt.  Here is the failing auto-generated query:

```
SELECT ST_AsMVT('l1', 256, 'geom', q) AS mvt FROM (
   SELECT ST_AsMVTGeom(ST_Transform(public.kalktest.geom, 3857), 
             TileBBox(4, 8, 4, 3857), 256, 0, false) geom , kalkinnhol
    FROM public.kalktest
    WHERE ST_Intersects(TileBBox(4, 8, 4, 3857), public.kalktest.geom)
) AS q

```
mvt_agg_transfn: geometry column cannot be null error: mvt_agg_transfn: geometry column cannot be null

My config:

```
  .use(postgismvt({
    lyr: {
      table: 'public.kalktest',
      geometry: 'geom',
//      type: 'circle',
      srid: 3857,
      minZoom: 0,
      maxZoom: 19,
      buffer: 0,
      fields: 'kalkinnhol',
      resolution: 256
    },
```

If I add 
`						WHERE geom IS NOT NULL
`
to the default query at index.js:104 it returns tiles.

**Comment by Stezii** [comment]
I tested against 3857 geometry and it stills works for me. Can you post your table schema? Are there any NULL values in the geom column? Normally, this should not be an issue.

**Comment by bjornreppen** [comment]
My schema: 

```
CREATE TABLE kalktest
(
  gid serial NOT NULL,
  objectid numeric,
  kalkinnhol numeric(10,0),
  geom geometry(MultiPolygon,32633),
  CONSTRAINT kalktest_pkey PRIMARY KEY (gid)
)
```

I'm feeling really dumb now.  Looks like ST_AsMVTGeom is modifying the geometry in my table.  If I do:

`SELECT ST_AsEWKT(GEOM) from kalktest order by gid limit 1`

`"SRID=3857;MULTIPOLYGON(((1024518.3618058 8910487.01134012, ...."

`SELECT ST_AsMVTGeom(public.kalktest.geom, TileBBox(2, 2, 1, 3857), 256, 0, false) FROM kalktest`
`SELECT ST_AsEWKT(GEOM) from kalktest order by gid limit 1`

"SRID=3857;MULTIPOLYGON(((26.178574318915 28.3185302087245, ..."

... seems like my coordinates gets manipulated by the call to ST_AsMVTGeom.   At least I know the problem is not with tilestrata-postgismvt.

**Comment by Stezii** [comment]
Modifying the geom is the purpse of ST_AsMVTGeom. It converts the coordinates from its global coordinate space (e. g. 3857) to the local tile coordinate space in the resolution you provide. This means, that the character length is greatly reduced leading a minimum data size. Of course, precision is still given since every tile is embedded into the global coordinate space with the help of the [slippy naming schema](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames). So nothing weird at this point. 

Can you provide the table schema, or even better: a illustrative tabel dump?

**Comment by bjornreppen** [comment]
I edited my comment above after you read it probably and pasted my table definition.  Thanks for helping.  

I have narrowed down the issue to 

`SELECT ST_AsMVTGeom(ST_Transform(geom, 3857), TileBBox(2, 2, 1, 3857), NULL,NULL,NULL) geom `

Every time I do the select I get a different result set.  If I query the geom column after running the select the data is changed (and then changed again the next time I select ST_AsMVTGeom).  Not the projection, just the data.  

I suspect some kind of memory corruption.  I am running my own build from trunk on postgresql 9.6.2.  I guess I'll have to head over to postgis issue tracker.

**Comment by Stezii** [comment]
Remember to provide the appropriate SRID (32633, according to your schema) in the parameter *srid* of the plugin configuration. 
Maybe there's an issue with multi geometries. Does this strange behavior still occur with single poly geometries?
